In [1]:
import pandas as pd
import glob

In [2]:
refs = pd.read_csv('..\\..\\refs\\refs.csv')
links = pd.DataFrame()

In [3]:
csv_files = glob.glob('../../database_export/links/links*.csv')
for csv_file in csv_files:
    df = pd.read_csv(csv_file)
    links = pd.concat([links, df])

In [4]:
refs

,ref,heRef,path,line_index
0,"Chayei Moharan, Introduction 1","חיי מוהר""ן, הקדמה, א,",אוצריא\חסידות\ברסלב\חיי מוהרן,4
1,"Chayei Moharan, Introduction 2","חיי מוהר""ן, הקדמה, ב,",אוצריא\חסידות\ברסלב\חיי מוהרן,5
2,"Chayei Moharan, Introduction 3","חיי מוהר""ן, הקדמה, ג,",אוצריא\חסידות\ברסלב\חיי מוהרן,6
3,"Chayei Moharan, Introduction 4","חיי מוהר""ן, הקדמה, ד,",אוצריא\חסידות\ברסלב\חיי מוהרן,7
4,"Chayei Moharan, Introduction 5","חיי מוהר""ן, הקדמה, ה,",אוצריא\חסידות\ברסלב\חיי מוהרן,8
...,...,...,...,...
2970658,Tosefta Terumot 10:14,"תוספתא תרומות י, יד,",אוצריא\תוספתא\דפוס וילנא\סדר זרעים\תוספתא תרומות,175
2970659,Tosefta Terumot 10:15,"תוספתא תרומות י, טו,",אוצריא\תוספתא\דפוס וילנא\סדר זרעים\תוספתא תרומות,176
2970660,Tosefta Terumot 10:16,"תוספתא תרומות י, טז,",אוצריא\תוספתא\דפוס וילנא\סדר זרעים\תוספתא תרומות,177
2970661,Tosefta Terumot 10:17,"תוספתא תרומות י, יז,",אוצריא\תוספתא\דפוס וילנא\סדר זרעים\תוספתא תרומות,178
2970662,Tosefta Terumot 10:18,"תוספתא תרומות י, יח,",אוצריא\תוספתא\דפוס וילנא\סדר זרעים\תוספתא תרומות,179

In [5]:
links

,Citation 1,Citation 2,Conection Type,Text 1,Text 2,Category 1,Category 2,Link Count
0,A Jewish Critique of the Philosophy of Martin ...,Berakhot 63b,NaN,A Jewish Critique of the Philosophy of Martin ...,Berakhot,Jewish Thought,Talmud,NaN
1,A Jewish Critique of the Philosophy of Martin ...,Shabbat 88b,NaN,A Jewish Critique of the Philosophy of Martin ...,Shabbat,Jewish Thought,Talmud,NaN
2,A New Israeli Commentary on Pirkei Avot 1:10:1-6,Pirkei Avot 1:10,commentary,A New Israeli Commentary on Pirkei Avot,Pirkei Avot,Mishnah,Mishnah,NaN
3,A New Israeli Commentary on Pirkei Avot 1:10:13,Sanhedrin 4a,NaN,A New Israeli Commentary on Pirkei Avot,Sanhedrin,Mishnah,Talmud,NaN
4,A New Israeli Commentary on Pirkei Avot 1:10:8,Pesachim 70b:5,NaN,A New Israeli Commentary on Pirkei Avot,Pesachim,Mishnah,Talmud,NaN
...,...,...,...,...,...,...,...,...
79778,NaN,NaN,NaN,Zakhor VeShamor,Zephaniah,NaN,NaN,1.0
79779,NaN,NaN,NaN,Zechariah,Zechariah,NaN,NaN,1.0
79780,NaN,NaN,NaN,Zechariah,Zevachim,NaN,NaN,1.0
79781,NaN,NaN,NaN,Zephaniah,Zohar Chadash,NaN,NaN,1.0
79782,NaN,NaN,NaN,Zohar,Zohar,NaN,NaN,1.0

add a reverse copy of the links and concat the two dataframes

In [6]:
reversed_links = pd.DataFrame()
reversed_links['Citation 1'] = links['Citation 2']
reversed_links['Citation 2'] = links['Citation 1']
reversed_links['Conection Type'] = links['Conection Type']
links = pd.concat([links, reversed_links])

In [7]:
merged_df_citation1 = links.merge(refs, left_on='Citation 1', right_on='ref', how='left')

In [8]:
merged_df_citation1['path'].unique().__len__()

5471

In [9]:
merged_df_citation1 = links.merge(refs, left_on='Citation 1', right_on='ref', how='left')
merged_df = merged_df_citation1.merge(refs, left_on='Citation 2', right_on='ref', how='left', suffixes=('_1', '_2'))

In [10]:
merged_df.head()

,Citation 1,Citation 2,Conection Type,Text 1,Text 2,Category 1,Category 2,Link Count,ref_1,heRef_1,path_1,line_index_1,ref_2,heRef_2,path_2,line_index_2
0,A Jewish Critique of the Philosophy of Martin ...,Berakhot 63b,NaN,A Jewish Critique of the Philosophy of Martin ...,Berakhot,Jewish Thought,Talmud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A Jewish Critique of the Philosophy of Martin ...,Shabbat 88b,NaN,A Jewish Critique of the Philosophy of Martin ...,Shabbat,Jewish Thought,Talmud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A New Israeli Commentary on Pirkei Avot 1:10:1-6,Pirkei Avot 1:10,commentary,A New Israeli Commentary on Pirkei Avot,Pirkei Avot,Mishnah,Mishnah,NaN,NaN,NaN,NaN,NaN,Pirkei Avot 1:10,"משנה אבות א, י,",אוצריא\משנה\סדר נזיקין\משנה אבות,12.0
3,A New Israeli Commentary on Pirkei Avot 1:10:13,Sanhedrin 4a,NaN,A New Israeli Commentary on Pirkei Avot,Sanhedrin,Mishnah,Talmud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A New Israeli Commentary on Pirkei Avot 1:10:8,Pesachim 70b:5,NaN,A New Israeli Commentary on Pirkei Avot,Pesachim,Mishnah,Talmud,NaN,NaN,NaN,NaN,NaN,Pesachim 70b:5,"פסחים ע:, ה,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,2165.0

In [11]:
result_df = merged_df.dropna(subset=['path_1', 'path_2'])

In [12]:
result_df

,Citation 1,Citation 2,Conection Type,Text 1,Text 2,Category 1,Category 2,Link Count,ref_1,heRef_1,path_1,line_index_1,ref_2,heRef_2,path_2,line_index_2
1042,Abarbanel on Amos 1:11:1,Genesis 49:28,NaN,Abarbanel on Amos,Genesis,Tanakh,Tanakh,NaN,Abarbanel on Amos 1:11:1,"אברבנאל על עמוס א, יא, א,",אוצריא\תנך\ראשונים על התנ״ך\אברבנאל\נביאים\אבר...,30.0,Genesis 49:28,"בראשית מט, כח,",אוצריא\תנך\תורה\בראשית,1552.0
1043,Abarbanel on Amos 1:11:1,Numbers 20:18,NaN,Abarbanel on Amos,Numbers,Tanakh,Tanakh,NaN,Abarbanel on Amos 1:11:1,"אברבנאל על עמוס א, יא, א,",אוצריא\תנך\ראשונים על התנ״ך\אברבנאל\נביאים\אבר...,30.0,Numbers 20:18,"במדבר כ, יח,",אוצריא\תנך\תורה\במדבר,746.0
1044,Abarbanel on Amos 1:11:1,Amos 1:11,commentary,Abarbanel on Amos,Amos,Tanakh,Tanakh,NaN,Abarbanel on Amos 1:11:1,"אברבנאל על עמוס א, יא, א,",אוצריא\תנך\ראשונים על התנ״ך\אברבנאל\נביאים\אבר...,30.0,Amos 1:11,"עמוס א, יא,",אוצריא\תנך\נביאים\עמוס,13.0
1046,Abarbanel on Amos 1:13:1,Proverbs 1:27,NaN,Abarbanel on Amos,Proverbs,Tanakh,Tanakh,NaN,Abarbanel on Amos 1:13:1,"אברבנאל על עמוס א, יג, א,",אוצריא\תנך\ראשונים על התנ״ך\אברבנאל\נביאים\אבר...,32.0,Proverbs 1:27,"משלי א, כז,",אוצריא\תנך\כתובים\משלי,29.0
1047,Abarbanel on Amos 1:13:1,Amos 1:13,commentary,Abarbanel on Amos,Amos,Tanakh,Tanakh,NaN,Abarbanel on Amos 1:13:1,"אברבנאל על עמוס א, יג, א,",אוצריא\תנך\ראשונים על התנ״ך\אברבנאל\נביאים\אבר...,32.0,Amos 1:13,"עמוס א, יג,",אוצריא\תנך\נביאים\עמוס,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7139804,Torah Temimah on Ecclesiastes 7:12:1,Pesachim 53b:9,NaN,NaN,NaN,NaN,NaN,NaN,Torah Temimah on Ecclesiastes 7:12:1,"תורה תמימה על קהלת ז, יב, א,",אוצריא\תנך\אחרונים על התנ״ך\תורה תמימה\כתובים\...,447.0,Pesachim 53b:9,"פסחים נג:, ט,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,1659.0
7139805,"Yismach Moshe, Ki Teitzei 14:3",Pesachim 53b:9,NaN,NaN,NaN,NaN,NaN,NaN,"Yismach Moshe, Ki Teitzei 14:3","ישמח משה, כי תצא, יד, ג,",אוצריא\חסידות\ספרי חסידות נוספים\ישמח משה,2735.0,Pesachim 53b:9,"פסחים נג:, ט,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,1659.0
7139806,"Sefer HaTashbetz, Part I 147:1",Pesachim 53b:9,NaN,NaN,NaN,NaN,NaN,NaN,"Sefer HaTashbetz, Part I 147:1","ספר התשב""ץ, חלק ראשון, קמז, א,",אוצריא\שות\ראשונים\ספר התשבץ,839.0,Pesachim 53b:9,"פסחים נג:, ט,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,1659.0
7139808,"Sefer HeArukh, Letter Mem 235",Pesachim 53b:9,NaN,NaN,NaN,NaN,NaN,NaN,"Sefer HeArukh, Letter Mem 235","ספר הערוך, אות המ""ם, רלה,",אוצריא\מילונים וספרי יעץ\מילונים\ספר הערוך,4310.0,Pesachim 53b:9,"פסחים נג:, ט,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,1659.0
7139809,Rif Pesachim 18a:1,Pesachim 53b:9,commentary,NaN,NaN,NaN,NaN,NaN,Rif Pesachim 18a:1,"רי""ף פסחים יח., א,",אוצריא\תלמוד\בבלי\ראשונים על התלמוד\ריף\סדר מו...,200.0,Pesachim 53b:9,"פסחים נג:, ט,",אוצריא\תלמוד\בבלי\סדר מועד\פסחים,1659.0

In [13]:
result_df = result_df[['path_1','line_index_1','heRef_2','path_2', 'line_index_2','Conection Type']]

In [14]:
unique_paths = result_df['path_1'].unique()

for path in unique_paths:
    path_df = result_df[result_df['path_1'] == path]
    path_df.drop(['path_1'], axis=1, inplace=True)
    path = path.split('\\')[-1]
    path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
    path_df.to_json(f'../links/{path}_links.json', orient='records')

C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df['path_2']=path_df['path_2'].map(lambda x: x.replace('..\\..\\refs\\',''))
C:\Users\Goldman\AppData\Local\Temp\ipykernel_3988\2716502835.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  path_df.drop(['path_1'], axis=1, inplace=True)